version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: curl https://api.github.com/repos/yatriks/circleci-checks-test/commits/$CIRCLE_SHA1/status
